name: build

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2


      - name: Setup | Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

      - name: Setup | Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          components: rustfmt

      - name: Build | Rustfmt
        run: cargo fmt -- --check


      - name: Build | Check
        run: cargo check --all

      - name: Build | Test
        run: cargo test

      # Run the CLI to ensure we don't have any subtle runtime issues.
      - name: Build | Run
        run: cargo run -- -h

      - name: Build | Build
        run: cargo build --release

      - name: Post Build | Prepare artifacts
        run: |
          cd target/release
          strip dot
          tar czvf ../../../dot dot
          cd -

      - name: Post Build | Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dot
          path: dot
